In [6]:
sudoku_solution=[[8, 6, 4, 3, 7, 1, 2, 5, 9],
 [3, 2, 5, 8, 4, 9, 7, 6, 1],
 [9, 7, 1, 2, 6, 5, 8, 4, 3],
 [4, 3, 6, 1, 9, 2, 5, 8, 7],
 [1, 9, 8, 6, 5, 7, 4, 3, 2],
 [2, 5, 7, 4, 8, 3, 9, 1, 6],
 [6, 8, 9, 7, 3, 4, 1, 2, 5],
 [7, 1, 3, 5, 2, 8, 6, 9, 4],
 [5, 4, 2, 9, 1, 6, 3, 7, 8]]


sudoku_game=[[0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]]


import numpy as np


 # Create the game_and_solution 3D array
game_and_solution = np.array([sudoku_game,sudoku_solution])

# Print game_and_solution
print(game_and_solution)

[[[0 0 4 3 0 0 2 0 9]
  [0 0 5 0 0 9 0 0 1]
  [0 7 0 0 6 0 0 4 3]
  [0 0 6 0 0 2 0 8 7]
  [1 9 0 0 0 7 4 0 0]
  [0 5 0 0 8 3 0 0 0]
  [6 0 0 0 0 0 1 0 5]
  [0 0 3 5 0 8 6 9 0]
  [0 4 2 9 1 0 3 0 0]]

 [[8 6 4 3 7 1 2 5 9]
  [3 2 5 8 4 9 7 6 1]
  [9 7 1 2 6 5 8 4 3]
  [4 3 6 1 9 2 5 8 7]
  [1 9 8 6 5 7 4 3 2]
  [2 5 7 4 8 3 9 1 6]
  [6 8 9 7 3 4 1 2 5]
  [7 1 3 5 2 8 6 9 4]
  [5 4 2 9 1 6 3 7 8]]]


In [9]:
sudoku_solution=[[8, 6, 4, 3, 7, 1, 2, 5, 9],
 [3, 2, 5, 8, 4, 9, 7, 6, 1],
 [9, 7, 1, 2, 6, 5, 8, 4, 3],
 [4, 3, 6, 1, 9, 2, 5, 8, 7],
 [1, 9, 8, 6, 5, 7, 4, 3, 2],
 [2, 5, 7, 4, 8, 3, 9, 1, 6],
 [6, 8, 9, 7, 3, 4, 1, 2, 5],
 [7, 1, 3, 5, 2, 8, 6, 9, 4],
 [5, 4, 2, 9, 1, 6, 3, 7, 8]]


sudoku_game=[[0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]]


import numpy as np
game_and_solution = np.array([sudoku_game,sudoku_solution])
# Create a second 3D array of another game and its solution
new_game_and_solution = np.array([sudoku_game,sudoku_solution])

# Create a 4D array of both game and solution 3D arrays
games_and_solutions = np.array([game_and_solution,new_game_and_solution])

# Print the shape of your 4D array
print(games_and_solutions.shape)

(2, 2, 9, 9)


In [ ]:
sudoku_solution=[[8, 6, 4, 3, 7, 1, 2, 5, 9],
 [3, 2, 5, 8, 4, 9, 7, 6, 1],
 [9, 7, 1, 2, 6, 5, 8, 4, 3],
 [4, 3, 6, 1, 9, 2, 5, 8, 7],
 [1, 9, 8, 6, 5, 7, 4, 3, 2],
 [2, 5, 7, 4, 8, 3, 9, 1, 6],
 [6, 8, 9, 7, 3, 4, 1, 2, 5],
 [7, 1, 3, 5, 2, 8, 6, 9, 4],
 [5, 4, 2, 9, 1, 6, 3, 7, 8]]


sudoku_game=[[0, 0, 4, 3, 0, 0, 2, 0, 9],
 [0, 0, 5, 0, 0, 9, 0, 0, 1],
 [0, 7, 0, 0, 6, 0, 0, 4, 3],
 [0, 0, 6, 0, 0, 2, 0, 8, 7],
 [1, 9, 0, 0, 0, 7, 4, 0, 0],
 [0, 5, 0, 0, 8, 3, 0, 0, 0],
 [6, 0, 0, 0, 0, 0, 1, 0, 5],
 [0, 0, 3, 5, 0, 8, 6, 9, 0],
 [0, 4, 2, 9, 1, 0, 3, 0, 0]]


import numpy as np
# Flatten sudoku_game
flattened_game = sudoku_game.flatten()

# Print the shape of flattened_game
print(flattened_game.shape)

# Reshape flattened_game back to a nine by nine array
reshaped_game = flattened_game.reshape((9,9))

# Print sudoku_game and reshaped_game
print(sudoku_game)
print(reshaped_game)