In [ ]:
# indexing&slicing
# adding and removing data

In [ ]:
tree_census = array([[     3, 501451,     24,      0],
       [     4, 501451,     20,      0],
       [     7, 501911,      3,      0],
       ...,
       [  1198, 227387,     11,      0],
       [  1199, 227387,     11,      0],
       [  1210, 227386,      6,      0]])

# Select all rows of block ID data from the second column 
block_ids = tree_census[:, 1]

# Print the first five block_ids

print(block_ids[:5])

In [ ]:
import numpy as np
new_trees = np.array([[1211, 227386, 20, 0], [1212, 227386, 8, 0]])

tree_census=np.array([[3 501451     24      0]
 [     4 501451     20      0]
 [     7 501911      3      0]
 ...
 [  1198 227387     11      0]
 [  1199 227387     11      0]
 [  1210 227386      6      0]])

# Print the shapes of tree_census and new_trees
print(tree_census.shape,new_trees.shape)

# Add rows to tree_census which contain data for the new trees
updated_tree_census = np.concatenate((tree_census,new_trees))
print(updated_tree_census)


In [ ]:
# Print the shapes of tree_census and trunk_stump_diameters
print(trunk_stump_diameters.shape, tree_census.shape)

# Reshape trunk_stump_diameters
reshaped_diameters = trunk_stump_diameters.reshape((1000, 1))

# Concatenate reshaped_diameters to tree_census as the last column
concatenated_tree_census = np.concatenate((tree_census,reshaped_diameters),axis=1)
print(concatenated_tree_census)

In [ ]:
# Delete the stump diameter column from tree_census
tree_census_no_stumps = np.delete(tree_census, 3, axis=1)

# Save the indices of the trees on block 313879
private_block_indices = np.where(tree_census[:,1] == 313879)

# Delete the rows for trees on block 313879 from tree_census_no_stumps
tree_census_clean = np.delete(tree_census_no_stumps,private_block_indices,axis=0)

# Print the shape of tree_census_clean
print(tree_census_clean.shape)