In [ ]:
# Splitting and stacking     

In [3]:
import numpy as np

monthly_sales=np.array([[ 4134, 23925,  8657],
       [ 4116, 23875,  9142],
       [ 4673, 27197, 10645],
       [ 4580, 25637, 10456],
       [ 5109, 27995, 11299],
       [ 5011, 27419, 10625],
       [ 5245, 27305, 10630],
       [ 5270, 27760, 11550],
       [ 4680, 24988,  9762],
       [ 4913, 25802, 10456],
       [ 5312, 25405, 13401],
       [ 6630, 27797, 18403]])

# Split monthly_sales into quarterly data
q1_sales, q2_sales, q3_sales, q4_sales = np.split(monthly_sales, 4)

# Print q1_sales
print(q1_sales)

# Stack the four quarterly sales arrays
quarterly_sales = np.stack([q1_sales, q2_sales, q3_sales, q4_sales ])
print(quarterly_sales)

[[ 4134 23925  8657]
 [ 4116 23875  9142]
 [ 4673 27197 10645]]
[[[ 4134 23925  8657]
  [ 4116 23875  9142]
  [ 4673 27197 10645]]

 [[ 4580 25637 10456]
  [ 5109 27995 11299]
  [ 5011 27419 10625]]

 [[ 5245 27305 10630]
  [ 5270 27760 11550]
  [ 4680 24988  9762]]

 [[ 4913 25802 10456]
  [ 5312 25405 13401]
  [ 6630 27797 18403]]]


In [ ]:

import numpy as np

rgb_array=np.array([[[  0,   0,   0],
        [117, 141, 175],
        [120, 145, 176],
        ...,
        [116, 147, 168],
        [117, 145, 167],
        [117, 145, 166]],

       [[  1,   1,   1],
        [126, 151, 182],
        [118, 143, 174],
        ...,
        [118, 149, 170],
        [116, 147, 168],
        [117, 145, 167]],

       [[  2,   2,   2],
        [128, 152, 180],
        [129, 153, 181],
        ...,
        [117, 147, 171],
        [114, 144, 168],
        [111, 141, 165]],

       ...,

       [[160, 160, 160],
        [191, 182, 167],
        [191, 180, 162],
        ...,
        [142, 135, 107],
        [155, 146, 115],
        [160, 147, 113]],

       [[161, 161, 161],
        [190, 181, 166],
        [201, 190, 172],
        ...,
        [144, 137, 109],
        [158, 149, 118],
        [164, 151, 117]],

       [[162, 162, 162],
        [163, 154, 139],
        [191, 180, 160],
        ...,
        [147, 140, 112],
        [164, 153, 121],
        [171, 158, 124]]])


# Split rgb_array into red, green, and blue arrays
red_array, green_array, blue_array = np.split(rgb_array, 3, axis=2)

# Create emphasized_blue_array
emphasized_blue_array = np.where(blue_array > blue_array.mean(), 255, blue_array)

# Print the shape of emphasized_blue_array
print(emphasized_blue_array.shape)

# Remove the trailing dimension from emphasized_blue_array
emphasized_blue_array_2D = emphasized_blue_array.reshape(675,844)

In [ ]:

import numpy as np
import matplotlib.pyplot as plt

rgb_array=np.array([[[  0,   0,   0],
        [117, 141, 175],
        [120, 145, 176],
        ...,
        [116, 147, 168],
        [117, 145, 167],
        [117, 145, 166]],

       [[  1,   1,   1],
        [126, 151, 182],
        [118, 143, 174],
        ...,
        [118, 149, 170],
        [116, 147, 168],
        [117, 145, 167]],

       [[  2,   2,   2],
        [128, 152, 180],
        [129, 153, 181],
        ...,
        [117, 147, 171],
        [114, 144, 168],
        [111, 141, 165]],

       ...,

       [[160, 160, 160],
        [191, 182, 167],
        [191, 180, 162],
        ...,
        [142, 135, 107],
        [155, 146, 115],
        [160, 147, 113]],

       [[161, 161, 161],
        [190, 181, 166],
        [201, 190, 172],
        ...,
        [144, 137, 109],
        [158, 149, 118],
        [164, 151, 117]],

       [[162, 162, 162],
        [163, 154, 139],
        [191, 180, 160],
        ...,
        [147, 140, 112],
        [164, 153, 121],
        [171, 158, 124]]])


# Split rgb_array into red, green, and blue arrays
red_array, green_array, blue_array = np.split(rgb_array, 3, axis=2)

# Create emphasized_blue_array
emphasized_blue_array = np.where(blue_array > blue_array.mean(), 255, blue_array)

# Print the shape of emphasized_blue_array
print(emphasized_blue_array.shape)

# Remove the trailing dimension from emphasized_blue_array
emphasized_blue_array_2D = emphasized_blue_array.reshape(675,844)

# Print the shapes of blue_array and emphasized_blue_array_2D
print(blue_array.shape, emphasized_blue_array_2D.shape)

# Reshape red_array and green_array
red_array_2D = red_array.reshape((675, 844))
green_array_2D = green_array.reshape((675, 844))

# Stack red_array_2D, green_array_2D, and emphasized_blue_array_2D
emphasized_blue_monet = np.stack([red_array_2D,green_array_2D,emphasized_blue_array_2D],axis=2)
plt.imshow(emphasized_blue_monet)
plt.show()  